### ISSUE TITLE
"Ok, resume game" and "Open backpack" not working.

### ISSUE THREAD

**Issue by MN-T-K** [Rorriis/center-hud#6]
Whenever you get a new item and either look at it or are forced to in mid-game, both the buttons to open the backpack and resume the game do not work. Hovering the mouse over both of them does not change their color. In-game, this can be mitigated by pressing ESC, although it will pop up with every death, and if looked at in the main menu, you must restart the game as it's essentially softlocked.

**Comment by Rorriis** [comment]
Fairly certain that's just jank TF2 behavior, as this HUD doesn't even alter the file that has that menu. Don't know how to fix that aside from maybe trying to opening the console and typing "hud_reloadscheme" if that happens.
