### ISSUE TITLE
Glitched Scoreboard

### ISSUE THREAD

**Issue by doonv** [Rorriis/center-hud#9]
When using center-hud-linux-v17b the scoreboard is completely broken:
![image](https://github.com/user-attachments/assets/e6914039-f5d6-4322-91f7-03bc2f5f53e3)

**Comment by doonv** [comment]
This is the non linux version, still scuffed but at least you can see something:
![image](https://github.com/user-attachments/assets/b2fb7e8f-f8ea-4ee2-b735-b97fb7ecdeae)

**Comment by Rorriis** [comment]
Could you try the most recent push? You download it [here](https://github.com/Rorriis/center-hud/archive/refs/heads/linux.zip)

**Comment by doonv** [comment]
> Could you try the most recent push? You can download it [here](https://github.com/Rorriis/center-hud/archive/refs/heads/linux.zip)

That works! Thanks
